# Generated by Django 4.0 on 2021-12-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product name')),
                ('company', models.CharField(max_length=200, verbose_name='Company')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image', models.ImageField(upload_to='static/products', verbose_name='Image')),
                ('number', models.IntegerField(blank=True, verbose_name='Number_products')),
                ('is_available', models.BooleanField(default=True)),
                ('output_form', models.CharField(blank=True, max_length=100)),
                ('substance_type', models.CharField(blank=True, max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.subcategory')),
            ],
        ),
    ]
